### PR TITLE
Treat every message as a reply

### PR DESCRIPTION
**Pull request by ahalekelly**
Thank you for this very useful bot! It was annoying to have to write !r at the beginning of every message in order to reply to someone. With this commit, any message in the channel that doesn't start with the prefix will be treated as a reply, leading to much more natural conversations.

### CODE REVIEW

**Comment by Dragory** [comment]
This is by design, as it allows for relevant discussion between moderators in the thread. Think of it as internal notes in conventional ticketing systems. We make extensive use of this functionality on the /r/Overwatch server.

Please change it to an option (default off) in your pull request instead, with a new alternative command (!note/!n, or such) for these internal notes, and I'll merge it!

**Comment by ahalekelly** [comment]
Alright, I can see why you would want that. I put your suggestion, as well as whether to be anonymous, and the auto response message, in the config file.

**Comment by Dragory** [comment]
This looks good! Thanks for the contribution!

**Comment by ahalekelly** [comment]
Thanks for being so responsive!

**Pull request merged**
