### PR TITLE
Add Docker Support

### PR DESCRIPTION
**Pull request by DevJeon1358**
Added Dockerfile.

**Process for creating the working image**
1. Make a config file (config.json) on app root directory.
2. Build a Image with command: `docker build -t IMAGETAG .`

### CODE REVIEW

**Comment by sporkwitch** [comment]
Would this be as generic / universal as the pm2 file? My concern is that we not have something added for a specific platform that requires ongoing maintenance and support. If this is an "add once and forget about it," like the pm2 file was, then I support this addition. If it has the potential to require fixes or changes if something else on the bot changes (other than the name of the launch file, obviously) I'd preder this be added and maintained on a site dedicated to docker containers, rather than the bot itself.

**Comment by Dragory** [comment]
I'm definitely a fan of having a dockerfile bundled in the repo. As far as I know, it should for the most part be an "add once and forget about it" addition, with the occasional Node.js version change in the dockerfile.

A few things:

* Creating a `config.json` (or `.ini`) is not necessary; config values can be passed as environment variables nowadays, which is probably more idiomatic when running the bot in a container anyway.
* The dockerfile doesn't use any shared volumes at the moment, right? Meaning that rebuilding the image (on e.g. a bot update) would also reset the database. Definitely need to have some solution to that.
* The dockerfile seems to be pulling in the Node.js 8 image and then installing `n` to install the current stable version of Node.js on top of that. Is that necessary? Additionally, since the repository includes a `.nvmrc` file, using `nvm` instead of `n` and then installing the version specified in the `.nvmrc` file would be more future proof.
* I'm not sure about the need to include yarn in there—running `npm ci` should be enough.

**Comment by sporkwitch** [comment]
Incrementing version numbers is trivial and requires no specific knowledge of docker, so I definitely support it. I noticed the lack of reference to storage as well, but didn't mention it because that's the part of docker I never managed to wrap my head around in my limited experience with it (hence the limited experience: anything I would do would need persistent storage and I couldn't figure out how to do that with docker in a timely enough manner.)

**Comment by DevJeon1358** [comment]
@Dragory Thank you for advice.
1. Creating a `config.json` is not a necessary. you can pass config value with ENV or `config.json`
2. That's a problem. Thanks for letting me know. I will make a volume with directory ( `/logs`, `/attachments`)
3. I didn't knew there was `.nvmrc` file in repo. I will change node install command with `nvm`
4. I will use `npm ci` instead of `yarn` command. thank you.

**Comment by GenryMg** [comment]
ok

**Comment by DevJeon1358** [comment]
Updated Dockerfile.

Changes:
1. Used `npm ci` instead of `yarn`
2. Made volume with directory (`/logs`, `/attachments`)
3. Changed `node` image tag to `latest`
I think `nvm` is not required, because `node:latest` image always the latest version.
4. Expose default port (8890)

**Comment by Dragory** [comment]
`node:latest` is always the latest, but the bot may not always support the latest version (e.g. it didn't support Node.js 13 initially). Grabbing the major version from .nvmrc and using that for the tag could work, but I'm not sure if Docker allows you to do that sort of magic in the Dockerfile. Using `nvm` would be the safest and most future-proof option.

The `/logs` folder is no longer used and is mainly kept for backwards compatibility\*. Logs, and other bot data such as snippets, are currently stored in `db/data.sqlite`, so making a volume for `/db` and `/attachments` would probably be the best.

Thank you for the work on this pull request!

\**(Early on in the bot's life, logs were stored as text files in `/logs`, but they have for a good while now been stored in the sqlite database instead. However, if I were to delete the folder from the repository, it might get deleted from people who still have old logs around and pull the latest changes in)*

**Comment by DevJeon1358** [comment]
We can use `node:lts-alpine` image. (lts version)
And I changed volume directory :)

I know it is best to use `nvm`, and I've tried to build with it.
But I'm expecting some problems now.
I'm trying to keep trying, but if I succeed, I'll send it pull-request again.

**Pull request closed without merging**
