### PR TITLE
update discord url

### PR DESCRIPTION
**Pull request by jaylac2000**
i know it wont make a difference since discord has not yet completely transferred over to the new domain, but it works.

### CODE REVIEW

**Comment by Monoverde888** [comment]
why

**Comment by dopeghoti** [comment]
Because the old domains are deprecated and will eventually no longer be maintained, so it's best to update references appropriately?

**Comment by cutepritam** [comment]
Disallowed intents specified what should i do

**Comment by mesub7** [comment]
Have a look at the pinned issue.

**Pull request merged**
