### PR TITLE
Add all options to Config

### PR DESCRIPTION
**Pull request by QuinnTDIP**

### CODE REVIEW

**Comment by LegitEzra** [comment]
Hello @Dragory likes to keep it simple. So people who are new with this can figure it out easily adding all the options will make new people overwhelmed in my opinion but the final decision is up to @Dragory

**Comment by Dragory** [comment]
Not a bad idea. Need to make it so it's not invalid by default, though (see: greetingAttachment). I wish you could use comments in JSON, would make the config file infinitely more readable.

**Comment by QuinnTDIP** [comment]
Ok, fixed that

**Comment by Dragory** [comment]
I chose to keep the example config to a bare minimum instead, in case I need to change some default values down the road. I added a subnote in the install instructions that mentions the list of configurable options at the end of the README. That means I can't merge this pull request, but thank you anyway!

**Pull request closed without merging**
