### PR TITLE
Update modmailbot-pm2.json

### PR DESCRIPTION
**Pull request by Eight8-7020**
Make the pm2 file work on windows, as well as linux.

### CODE REVIEW

**Comment by mesub7** [comment]
See the commits [here](https://github.com/Dragory/modmailbot/pull/398).

**Comment by dopeghoti** [comment]
Has this been tested on MacOS, Linux, _and_ Windows?  It'd be a shame to start playing whack-a-mole and fix one RTE only to break another.

**Comment by Eight8-7020** [comment]
I have tested it on Linux and Windows: it works, and Xx_FishyZ_xX#6969 has tested it on MacOS.

**Comment by mesub7** [comment]
I can confirm it has now been tested on all 3 mainstream operating systems.

**Pull request merged**
