### PR TITLE
Fix typingProxy + Add some features

### PR DESCRIPTION
**Pull request by Akinator31**
I fixed an issue with the TypingProxy module that just wasn't working at all. The problem was that the "if" which checks that typingProxy is enabled in the config file, was trying to check that the "channel" parameter was an instance of the Eris PrivateChannel class. However, it always returned False due to a problem in Eris's code. 

if (config.typingProxy && (channel instanceof Eris.PrivateChannel) TO if (config.typingProxy && !(channel instanceof Eris.GuildChannel))

To solve this problem, I simply checked that the "channel" was not a server message and it worked.

### CODE REVIEW

**Comment by rubyowo** [comment]
You should create separate PRs for different features

**Comment by zayKenyon** [comment]
> Yes but I have to create different fork..

No you don't! You need to create different branches. Normally master (or main, but master in this case) is preserved with new branches deriving from that. Realistically, if you want to get this merged, you will make life easy for the maintainers and make separate PRs for different features. 

I don't know your exact setup but it looks like you're trying to merge your master. I would suggest making a new branch from your latest commit, stashing the secondary features, and then [editing](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request) your PR to reflect this. You can use these stashed commits to form their own branches, which should become PRs in their own right.

**Comment by Akinator31** [comment]
Oh yes, you're right, I'll do that. Thanks for the tip ;)

**Comment by zayKenyon** [comment]
Thank you, the documentation in #806 is great!

**Comment by Akinator31** [comment]
Thank you ;)

**Pull request closed without merging**
