### PR TITLE
This is a simple script to start the bot.

### PR DESCRIPTION
**Pull request by LegitEzra**
Anyone on windows who has the dependencies and node.js installed can run this and the bot will start. As long as this batch file is in the bots root directory it will start the bot. If the /src folder is renamed the batch file will not run

### CODE REVIEW

**Comment by Dragory** [comment]
Oh, this looks good, thanks! Can you change it so it instead `cd`'s into the dir and runs `npm start` instead? That's the way I recommend starting the bot in the README nowadays.

**Comment by LegitEzra** [comment]
@Dragory fixed it could you also checkout my other pull request?

**Comment by LegitEzra** [comment]
If you would like I can add an option to pick a color for the text
ex. Enter G into the command prompt and the color would be green

**Comment by Dragory** [comment]
Maybe the start-up script should run npm install every time you start the bot? Since if all packages are installed, it's just a quick check and shouldn't really slow down the start-up. This would then technically do what #21 does as well.

**Comment by LegitEzra** [comment]
Okay all add the install check

**Comment by LegitEzra** [comment]
@Dragory its ready let me know if I should add color.

**Comment by LegitEzra** [comment]
Since you wanted me to use npm start instead of the src/index.js I cant clear the console messages during npm or rename the console to Modmailbot Console.

**Comment by LegitEzra** [comment]
@Dragory In case you forgot!

**Comment by Dragory** [comment]
Hey, haven't forgotten! Just busy with something right now. I'll get back to this ASAP.

**Comment by LegitEzra** [comment]
Okay @Dragory

**Comment by Ragnarok345** [comment]
Any chance of getting one of these made for Mac?

**Comment by sporkwitch** [comment]
@Ragnarok345 http://www.tldp.org/LDP/abs/html/dosbatch.html
Though really there's no need to script this stuff; it's not like it automagically restarts the bot if it crashes, it just saves you a couple commands.

I'd recommend instead just checking for updates occasionally, and running the bot in a tmux session so you can detach and close the window, but still get back to it later (you'll need homebrew to install tmux https://brew.sh/ )

**Comment by Ragnarok345** [comment]
@sporkwitch Thanks for the answer, though I never saw it until now. Is there a way to make this bot auto-restart if it goes down in Terminal for Mac?

**Pull request closed without merging**
